Developer-Toolbox/Models/LearningPath.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Developer_Toolbox.Models
{
    public class LearningPath
    {
        [Key]
        public int Id { get; set; }

        [Required(ErrorMessage = "Learning path required!")]
        public string Name { get; set; }
        public string? UserId { get; set; }
        public ApplicationUser? User { get; set; }
        public virtual ICollection<LockedExercise>? LockedExercises { get; set; }

        [Required(ErrorMessage = "Description of learning path is required!")]
        public string? Description { get; set; }

    }
}

Developer-Toolbox/Controllers/LearningPathsController.cs
using Developer_Toolbox.Data;
using Developer_Toolbox.Models;
using Developer_Toolbox.Repositories;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace Developer_Toolbox.Controllers
{
    public class LearningPathsController : Controller
    {
        private readonly ApplicationDbContext db;
        private IWebHostEnvironment _env;

        private readonly UserManager<ApplicationUser> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;
        
        public LearningPathsController(ApplicationDbContext context,
            IWebHostEnvironment environment,
            UserManager<ApplicationUser> userManager,
            RoleManager<IdentityRole> roleManager)
        {
            db = context;
            _userManager = userManager;
            _roleManager = roleManager;
            _env = environment;
        }

        //Conditii de afisare a butoanelor de editare si stergere
        private void SetAccessRights()
        {
            ViewBag.IsModerator = User.IsInRole("Moderator");

            ViewBag.IsAdmin = User.IsInRole("Admin");

            ViewBag.CurrentUser = _userManager.GetUserId(User);

            // verificam daca are profilul complet
            bool userProfilComplet = false;

            if (_userManager.GetUserId(User) != null)
            {
                // userConectat = true;
                if (db.ApplicationUsers.Find(_userManager.GetUserId(User)).FirstName != null)
                    userProfilComplet = true;
            }

            ViewBag.UserProfilComplet = userProfilComplet;
        }


        public IActionResult Index()
        {
            SetAccessRights();
            if (TempData.ContainsKey("message"))
            {
                ViewBag.Message = TempData["message"];
                ViewBag.MessageType = TempData["messageType"];
            }
            var paths = db.LearningPaths;
            ViewBag.Paths = paths;
            return View(paths);
        }

        [Authorize(Roles = "Admin,Moderator")]
        public ActionResult New()
        {
            //transmitem mesajele primite in view
            if (TempData.ContainsKey("message"))
            {
                ViewBag.Message = TempData["message"];
                ViewBag.MessageType = TempData["messageType"];
            }

            // noul path
            LearningPath path = new LearningPath();

            return View(path);
        }

        [Authorize(Roles = "Admin,Moderator")]
        [HttpPost]
        public async Task<IActionResult> New(LearningPath path)
        {
            SetAccessRights();

            path.UserId = _userManager.GetUserId(User);

            
            if (ModelState.IsValid)
            {

                
                db.LearningPaths.Add(path);
               
                db.SaveChanges();

                TempData["message"] = "The learning path has been added";
                TempData["messageType"] = "alert-success";

                return RedirectToAction("Index");
            }

            else
            {
                foreach (var modelStateEntry in ModelState.Values)
                {
                    foreach (var error in modelStateEntry.Errors)
                    {
                        // pentru debug
                        var errorMessage = error.ErrorMessage;
                        var exception = error.Exception;
                    }
                }
                return View(path);
            }
        }

        public IActionResult Show(int id)
        {
            SetAccessRights();


            //transmitem mesajele primite in view
            if (TempData.ContainsKey("message"))
            {
                ViewBag.Message = TempData["message"];
                ViewBag.MessageType = TempData["messageType"];
            }

            SetAccessRights();

            // preluam path-ul cerut
            LearningPath path = db.LearningPaths.Include("LockedExercises")
                                            .Include("User")
                                            .Where(path => path.Id == id)
                                            .First();

            ViewBag.Ex = db.LockedExercises.Include("User").Where(ex => ex.LearningPathId == id);

            ViewBag.LastEx = db.LockedExercises.Include("User").Where(ex => ex.LearningPathId == id
                              && db.LockedSolutions.Any(s => s.LockedExerciseId == ex.Id && s.Score == 100 && s.UserId== _userManager.GetUserId(User)))
                              .OrderByDescending(ex => ex.Id)
                              .FirstOrDefault();



            return View(path);

        }

        [Authorize(Roles = "Admin,Moderator")]
        [HttpPost]
        public ActionResult Delete(int id)
        {
            // preluam path ul care trebuie sters
            LearningPath path = db.LearningPaths.Include("LockedExercises")
                                             .Where(c => c.Id == id)
                                             .First();

            if (path.UserId == _userManager.GetUserId(User) || User.IsInRole("Admin"))
            {
              

               
                db.LearningPaths.Remove(path);

                // commit
                db.SaveChanges();

                TempData["message"] = "The path has been deleted";
                TempData["messageType"] = "alert-success";
                return RedirectToAction("Index");
            }
            else
            {
                TempData["message"] = "You're unable to delete a path you didn't add!";
                TempData["messageType"] = "alert-danger";
                return RedirectToAction("Index");
            }

        }

        [Authorize(Roles = "Admin,Moderator")]
        public ActionResult Edit(int id)
        {
            //transmitem mesajele primite in view
            if (TempData.ContainsKey("message"))
            {
                ViewBag.Message = TempData["message"];
                ViewBag.MessageType = TempData["messageType"];
            }

            LearningPath path = db.LearningPaths.Find(id);

            //restrictionam permisiunile
            if (path.UserId == _userManager.GetUserId(User) || User.IsInRole("Admin"))
            {
                return View(path);
            }
            else
            {
                TempData["message"] = "You're unable to modify a path you didn't add!";
                TempData["messageType"] = "alert-danger";
                return RedirectToAction("Index");
            }
        }

        [Authorize(Roles = "Admin,Moderator")]
        [HttpPost]
        public async Task<IActionResult> Edit(int id, LearningPath requestPath)
        {
            
            LearningPath path = db.LearningPaths.Find(id);


            if (ModelState.IsValid)
            {
                if (path.UserId == _userManager.GetUserId(User) || User.IsInRole("Admin"))
                {


                    // modificam informatiile
                    path.Name = requestPath.Name;
                    path.Description = requestPath.Description;

                 

                    //commit
                    db.SaveChanges();

                    TempData["message"] = "The path has been edited";
                    TempData["messageType"] = "alert-success";
                    return RedirectToAction("Index");
                }
                else
                {
                    TempData["message"] = "You're unable to modify a path you didn't add!";
                    TempData["messageType"] = "alert-danger";
                    return RedirectToAction("Index");
                }

            }
            else
            {
                return View(requestPath);
            }
        }

    }
}

Developer-Toolbox/Views/LearningPaths/Edit.cshtml
@model Developer_Toolbox.Models.LearningPath

<link rel="stylesheet" href="~/css/form.css" asp-append-version="true" />


<div class="container mt-5">
    @if (TempData.ContainsKey("message"))
    {
        <h4 class="@ViewBag.MessageType p-3 rounded-3 text-center mb-5">@ViewBag.Message</h4>
    }
    <div class="row justify-content-center">
        <div class="col-lg-10 col-md-12 col-sm-12">
            <div class="card shadow-lg">
                <div class="card-body">
                    <h3 class="card-title text-center mb-4">Edit learning path</h3>
                    <form method="post" action="/LearningPaths/Edit/@Model.Id">
                        <div class="mb-3">
                            @Html.Label("Name", "Name")

                            @Html.TextBox("Name", null, new { @class = "form-control" })

                            @Html.ValidationMessageFor(m => m.Name, null, new { @class = "text-danger" })
                        </div>
                        <div class="mb-3">
                            @Html.Label("Description", "Description")

                            @Html.TextBox("Description", null, new { @class = "form-control" })

                            @Html.ValidationMessageFor(m => m.Description, null, new { @class = "text-danger" })
                        </div>
                        <!-- Submit Button -->
                        <div class="text-center">
                            <button type="submit" class="btn btn-primary btn-lg">Save changes</button>
                            <div id="formFeedback" class="mt-3"></div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

Developer-Toolbox/Views/LearningPaths/Index.cshtml
@model IEnumerable<Developer_Toolbox.Models.LearningPath>

@{
    ViewData["Title"] = "Index";
}

<link rel="stylesheet" href="~/css/exercises.css" asp-append-version="true" />
<link rel="stylesheet" href="~/css/feature_section.css" asp-append-version="true" />

<section class="features-area features-one">

    @if (TempData.ContainsKey("message"))
    {
        <h4 class="@ViewBag.MessageType p-3 rounded-3 text-center mb-5">@ViewBag.Message</h4>
    }
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-6">
                <div class="section-title text-center">
                    <h3 class="title">Learning paths</h3>
                    
                </div>
                <!-- row -->
            </div>
        </div>
        <div class="row justify-content-center">
            <div class="col d-flex justify-content-between align-items-center" style="margin-right: 2%">    
                <a class="btn btn-outline-primary py-sm-3 px-sm-4 rounded-pill me-3" style="font-weight:bold;" href="/LockedSolutions/Index" role="button"> My submissions</a>
                @if (ViewBag.IsModerator || ViewBag.IsAdmin)
                {
                    <a class="btn btn-outline-primary py-sm-3 px-sm-4 rounded-pill me-3" style="font-weight:bold;" href="/LearningPaths/New" role="button"> + Create Learning Path</a>
                }
            </div>
        </div>
        <!-- row -->
        <div class="container py-5">
            <div class="row g-5 d-flex justify-content-start">
                @foreach (var item in ViewBag.Paths)
                {
                    <div class="col" style="max-width: fit-content">
                        <div class="card exercise-card border-0 rounded-4 shadow-sm">
                            <div class="position-relative p-2">
                                <span class="badge bg-primary badge-custom">Created by: @item.User?.UserName</span>
                            </div>
                            <div class="card-body p-4 d-flex flex-column justify-content-around">
                                <h5 class="card-title mb-3 fw-bold text-center">@item.Name</h5>
                                <p class="card-text text-center text-muted mb-4">
                                    @item.Description
                                </p>

                                @if (ViewBag.IsAdmin || ViewBag.CurrentUser == item.UserId)
                                {
                                    <div style="display:flex; justify-content: space-between;">
                                        <a asp-action="Edit" asp-controller="LearningPaths" asp-route-id="@item.Id" class="btn btn-no-outline">
                                            <i class="lni lni-write" style="font-size: x-large; color: var(--primary)"></i>
                                        </a>
                                        <a class="btn btn-outline-primary py-2 px-5 rounded-pill" style="font-weight: bold; font-size: small"
                                           asp-controller="LearningPaths" asp-action="Show" asp-route-id="@item.Id">
                                            Start Learning
                                        </a>
                                        <form method="post" asp-action="Delete" asp-controller="LearningPaths" asp-route-id="@item.Id">
                                            <button type="submit" class="btn btn-no-outline">
                                                <i class="lni lni-trash-can" style="font-size: x-large; color: var(--primary)"></i>
                                            </button>
                                        </form>
                                    </div>
                                }
                                else
                                {
                                    <a class="btn btn-outline-primary py-2 px-5 rounded-pill" style="font-weight: bold; font-size: small"
                                       asp-controller="LearningPaths" asp-action="Show" asp-route-id="@item.Id">
                                        Start Learning
                                    </a>
                                }
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
    <!-- container -->

 
</section>

Developer-Toolbox/Views/LearningPaths/New.cshtml
@model Developer_Toolbox.Models.LearningPath

@{
    ViewBag.Title = "Create New Learning Path";
}
<link rel="stylesheet" href="~/css/form.css" asp-append-version="true" />

<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-lg-10 col-md-12 col-sm-12">
            <div class="card shadow-lg">
                <div class="card-body">
                    <h3 class="card-title text-center mb-4">Create New Learning Path</h3>
                    <form method="post" action="/LearningPaths/New">
                        <div class="mb-3">
                            @Html.Label("Name", "Name")
                            @Html.TextBox("Name", null, new { @class = "form-control" })
                            @Html.ValidationMessage("Name", null, new { @class = "text-danger" })
                        </div>
                        <div class="mb-3">
                            @Html.Label("Description", "Description")
                            @Html.TextArea("Description", null, new { @class = "form-control" })
                            @Html.ValidationMessage("Description", null, new { @class = "text-danger" })
                        </div>

                        <!-- Submit Button -->
                        <div class="text-center">
                            <button type="submit" class="btn btn-primary btn-lg">Submit</button>
                            <div id="formFeedback" class="mt-3"></div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

Developer-Toolbox/Views/LearningPaths/Show.cshtml
@model Developer_Toolbox.Models.LearningPath

@{
    ViewData["Title"] = "Show Learning Path";
}
<br />

@if (TempData.ContainsKey("message"))
{
    <h4 class="@ViewBag.MessageType p-3 rounded-3 text-center mb-5">@ViewBag.Message</h4>
}

<div style="position: relative; height: 50px;">
    <a href="/LearningPaths/Index"
       style="background-color: #3B82F6; color: white; padding: 10px 20px; border-radius: 5px; text-decoration: none; display: inline-block; font-weight: bold; transition: background-color 0.3s; position: absolute; left: 20px;"
       onmouseover="this.style.backgroundColor='#2563EB';"
       onmouseout="this.style.backgroundColor='#3B82F6';">
        Back to All Paths
    </a>

    @if (ViewBag.IsModerator || ViewBag.IsAdmin)
    {
        <a href="/LockedExercises/New"
           style="background-color: #3B82F6; color: white; padding: 10px 20px; border-radius: 5px; text-decoration: none; display: inline-block; font-weight: bold; transition: background-color 0.3s; position: absolute; right: 30px;"
           onmouseover="this.style.backgroundColor='#2563EB';"
           onmouseout="this.style.backgroundColor='#3B82F6';">
            Add Exercise
        </a>
    }
</div>

<br />
<br />

    @if (ViewBag.Ex != null)
    {
      var counter = 0;
    <div class="difficulty-section mb-4">
            <div class="row row-cols-1 row-cols-md-2 g-3">
                @foreach (var exercise in ViewBag.Ex)
               {
                counter++;
                @if ((ViewBag.LastEx == null && counter == 1) || (ViewBag.LastEx != null && exercise.Id <= ViewBag.LastEx.Id+1))
                       { <div class="col">
                        <div class="card" style="transition: all 0.3s ease; border: 1px solid #e0e0e0; box-shadow: 0 2px 4px rgba(0,0,0,0.1);" onmouseover="this.style.boxShadow='0 8px 16px rgba(13, 110, 253, 0.2)'" onmouseout="this.style.boxShadow='0 2px 4px rgba(0,0,0,0.1)'">
                                <a asp-action="Show" asp-controller="LockedExercises" asp-route-id="@exercise.Id" style="text-decoration: none; outline: none;">
                                    <div class="card-header d-flex" style="justify-content: space-between; align-items: center">
                                        <h3 style="color:black;">@exercise.Title</h3>
                                        <span class="badge badge-primary" style="background-color:#0d6efd">@exercise.Difficulty</span>
                                    </div>
                                </a>

                                <div class="card-body">
                                    <h5 class="card-title">@exercise.Summary</h5>
                                    @if (exercise.UserId == ViewBag.CurrentUser || ViewBag.IsAdmin)
                                    {
                                        <div style="display:flex; justify-content: space-between;">
                                            <a asp-action="Edit" asp-controller="LockedExercises" asp-route-id="@exercise.Id">
                                                <svg style="width:20px; height:20px;" fill="none" stroke="#FF0000" stroke-width="1.5" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" aria-hidden="true">
                                                    <path stroke-linecap="round" stroke-linejoin="round" d="M16.862 4.487l1.687-1.688a1.875 1.875 0 112.652 2.652L10.582 16.07a4.5 4.5 0 01-1.897 1.13L6 18l.8-2.685a4.5 4.5 0 011.13-1.897l8.932-8.931zm0 0L19.5 7.125M18 14v4.75A2.25 2.25 0 0115.75 21H5.25A2.25 2.25 0 013 18.75V8.25A2.25 2.25 0 015.25 6H10"></path>
                                                </svg>
                                            </a>
                                            <form method="post" asp-action="Delete" asp-controller="LockedExercises" asp-route-id="@exercise.Id">
                                                <button type="submit" class="btn btn-no-outline">
                                                    <svg style="width:20px; height:20px;" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="#FF0000">
                                                        <path stroke-linecap="round" stroke-linejoin="round" d="M14.74 9l-.346 9m-4.788 0L9.26 9m9.968-3.21c.342.052.682.107 1.022.166m-1.022-.165L18.16 19.673a2.25 2.25 0 01-2.244 2.077H8.084a2.25 2.25 0 01-2.244-2.077L4.772 5.79m14.456 0a48.108 48.108 0 00-3.478-.397m-12 .562c.34-.059.68-.114 1.022-.165m0 0a48.11 48.11 0 013.478-.397m7.5 0v-.916c0-1.18-.91-2.164-2.09-2.201a51.964 51.964 0 00-3.32 0c-1.18.037-2.09 1.022-2.09 2.201v.916m7.5 0a48.667 48.667 0 00-7.5 0" />
                                                    </svg>
                                                </button>
                                            </form>
                                        </div>
                                    }
                                </div>
                            </div>
                    </div>

                }
                else
                {
                    <div class="col">
                        <div class="card" style="opacity: 0.7; position: relative;">
                            <!-- overlay pentru hover message -->
                            <div style="display: none; position: absolute;
            top: 50%; left: 50%;
            transform: translate(-50%, -50%);
            width: 200px; height: 100px;
            background: rgba(0,0,0,0.7);
            color: white; z-index: 10;
            border-radius: 8px;
            justify-content: center;
            align-items: center;
            text-align: center;"
                                 class="hover-message">
                                Solve the previous exercise to unlock this one
                            </div>

                            <!-- Icon lacat în mijlocul cardului -->
                            <div style="position: absolute; top: 50%; left: 50%; transform: translate(-50%, -50%);
                    z-index: 5;">
                                <svg xmlns="http://www.w3.org/2000/svg" width="40" height="40" fill="currentColor"
                                     class="bi bi-lock-fill" viewBox="0 0 16 16" style="color: #666;">
                                    <path d="M8 1a2 2 0 0 1 2 2v4H6V3a2 2 0 0 1 2-2zm3 6V3a3 3 0 0 0-6 0v4a2 2 0 0 0-2 2v5a2 2 0 0 0 2 2h6a2 2 0 0 0 2-2V9a2 2 0 0 0-2-2z" />
                                </svg>
                            </div>

                            <!-- Continutul original al cardului cu opacity redus -->
                            <a asp-action="Show" asp-controller="LockedExercises" asp-route-id="@exercise.Id"
                               style="text-decoration: none; outline: none; pointer-events: none;">
                                <div class="card-header d-flex" style="justify-content: space-between; align-items: center">
                                    <h3 style="color:black;">@exercise.Title</h3>
                                    <span class="badge badge-primary" style="background-color:#0d6efd">@exercise.Difficulty</span>
                                </div>
                            </a>
                            <div class="card-body">
                                <h5 class="card-title">@exercise.Summary</h5>
                                @if (exercise.UserId == ViewBag.CurrentUser || ViewBag.IsAdmin)
                                {
                                    <div style="display:flex; justify-content: space-between;">
                                        <a asp-action="Edit" asp-controller="LockedExercises" asp-route-id="@exercise.Id">
                                            <svg style="width:20px; height:20px;" fill="none" stroke="#FF0000" stroke-width="1.5" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" aria-hidden="true">
                                                <path stroke-linecap="round" stroke-linejoin="round" d="M16.862 4.487l1.687-1.688a1.875 1.875 0 112.652 2.652L10.582 16.07a4.5 4.5 0 01-1.897 1.13L6 18l.8-2.685a4.5 4.5 0 011.13-1.897l8.932-8.931zm0 0L19.5 7.125M18 14v4.75A2.25 2.25 0 0115.75 21H5.25A2.25 2.25 0 013 18.75V8.25A2.25 2.25 0 015.25 6H10"></path>
                                            </svg>
                                        </a>
                                        <form method="post" asp-action="Delete" asp-controller="LockedExercises" asp-route-id="@exercise.Id">
                                            <button type="submit" class="btn btn-no-outline">
                                                <svg style="width:20px; height:20px;" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="#FF0000">
                                                    <path stroke-linecap="round" stroke-linejoin="round" d="M14.74 9l-.346 9m-4.788 0L9.26 9m9.968-3.21c.342.052.682.107 1.022.166m-1.022-.165L18.16 19.673a2.25 2.25 0 01-2.244 2.077H8.084a2.25 2.25 0 01-2.244-2.077L4.772 5.79m14.456 0a48.108 48.108 0 00-3.478-.397m-12 .562c.34-.059.68-.114 1.022-.165m0 0a48.11 48.11 0 013.478-.397m7.5 0v-.916c0-1.18-.91-2.164-2.09-2.201a51.964 51.964 0 00-3.32 0c-1.18.037-2.09 1.022-2.09 2.201v.916m7.5 0a48.667 48.667 0 00-7.5 0" />
                                                </svg>
                                            </button>
                                        </form>
                                    </div>
                                }
                            </div>
                        </div>
                    </div>

                    <style>
                        .card:hover .hover-message {
                            display: flex !important;
                        }
                    </style>
                }
                    }

        </div>
    </div>
    }