Developer-Toolbox/Models/Category.cs
using System.ComponentModel.DataAnnotations;

namespace Developer_Toolbox.Models
{
    public class Category
    {
        [Key]
        public int Id { get; set; }

        [Required(ErrorMessage = "The name of the category is mandatory")]
        public string? CategoryName { get; set; }
        public string? UserId { get; set; }
        [Required(ErrorMessage = "The logo of the category is mandatory")]
        public string? Logo { get; set; } = "/images/categories/default.png";
        public virtual ICollection<Exercise>? Exercises { get; set; }

        public virtual ICollection<Badge>? RelatedBadges { get; set; }
    }
}

Developer-Toolbox/Controllers/CategoriesController.cs
using Developer_Toolbox.Data;
using Developer_Toolbox.Models;
using Developer_Toolbox.Repositories;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.IO;

namespace Developer_Toolbox.Controllers
{
    public class CategoriesController : Controller
    {
        private readonly ApplicationDbContext db;
        private IWebHostEnvironment _env;

        private readonly UserManager<ApplicationUser> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly ICategoryRepository _categoryRepository;

        public CategoriesController(ApplicationDbContext context,
            IWebHostEnvironment environment,
            UserManager<ApplicationUser> userManager,
            RoleManager<IdentityRole> roleManager, ICategoryRepository categoryRepository)
        {
            db = context;
            _userManager = userManager;
            _roleManager = roleManager;
            _env = environment;
            _categoryRepository = categoryRepository;
        }

        //Conditii de afisare a butoanelor de editare si stergere
        private void SetAccessRights()
        {
            ViewBag.IsModerator = User.IsInRole("Moderator");

            ViewBag.IsAdmin = User.IsInRole("Admin");

            ViewBag.CurrentUser = _userManager.GetUserId(User);

            // verificam daca are profilul complet
            bool userProfilComplet = false;

            if (_userManager.GetUserId(User) != null)
            {
                // userConectat = true;
                if (db.ApplicationUsers.Find(_userManager.GetUserId(User)).FirstName != null)
                    userProfilComplet = true;
            }
            
            ViewBag.UserProfilComplet = userProfilComplet;
        }


        public IActionResult Index()
        {
            SetAccessRights();

            // transmitem mesajele primite in view
            if (TempData.ContainsKey("message"))
            {
                ViewBag.Message = TempData["message"];
                ViewBag.MessageType = TempData["messageType"];
            }


            // preluam categoriile din baza de date 
            var categories = from category in db.Categories
                             orderby category.CategoryName
                             select category;

            // transmitem categoriile in view
            ViewBag.Categories = categories;

            return View();
        }


        [Authorize(Roles = "Admin,Moderator")]
        public ActionResult New()
        {
            //transmitem mesajele primite in view
            if (TempData.ContainsKey("message"))
            {
                ViewBag.Message = TempData["message"];
                ViewBag.MessageType = TempData["messageType"];
            }

            // noua categorie
            Category cat = new Category();

            return View(cat);
        }

        [Authorize(Roles = "Admin,Moderator")]
        [HttpPost]
        public async Task<IActionResult> New(Category cat, IFormFile file)
        {
            SetAccessRights();

            cat.UserId = _userManager.GetUserId(User);

            // incercam sa uploadam imaginea pentru logo
            var res = await SaveImage(file);

            if (res == null)
            {
                ModelState.AddModelError("Logo", "Please load a jpg, jpeg, png, and gif file type.");
            } 
            else
            {
               cat.Logo = res;
            }

            if (ModelState.IsValid)
            {

                //add the object received to database
                db.Categories.Add(cat);

                //commit
                db.SaveChanges();

                TempData["message"] = "The category has been added";
                TempData["messageType"] = "alert-success";

                return RedirectToAction("Index");
            }

            else
            {
                foreach (var modelStateEntry in ModelState.Values)
                {
                    foreach (var error in modelStateEntry.Errors)
                    {
                        // pentru debug
                        var errorMessage = error.ErrorMessage;
                        var exception = error.Exception;
                    }
                }
                return View(cat);
            }
        }

        [Authorize(Roles = "Admin,Moderator")]
        public ActionResult Edit(int id)
        {
            //transmitem mesajele primite in view
            if (TempData.ContainsKey("message"))
            {
                ViewBag.Message = TempData["message"];
                ViewBag.MessageType = TempData["messageType"];
            }

            // preluam categoria cautata
            Category category = db.Categories.Find(id);

            //restrictionam permisiunile
            if (category.UserId == _userManager.GetUserId(User) || User.IsInRole("Admin"))
            {
                return View(category);
            }
            else
            {
                TempData["message"] = "You're unable to modify a category you didn't add!";
                TempData["messageType"] = "alert-danger";
                return RedirectToAction("Index");
            }
        }

        [Authorize(Roles = "Admin,Moderator")]
        [HttpPost]
        public async Task<IActionResult> Edit(int id, Category requestCategory, IFormFile file)
        {
            // preluam categoria cautata
            Category category = db.Categories.Find(id);

            // incercam sa uploadam imaginea pentru logo
            var res = await SaveImage(file);

            if (res == null)
            {
                ModelState.AddModelError("Logo", "Please load a jpg, jpeg, png or gif file type.");
            }


            if (ModelState.IsValid)
            {
                if (category.UserId == _userManager.GetUserId(User) || User.IsInRole("Admin"))
                {
                    //stergem imaginea logo anterioara din folder-ul imgs
                    string path = Path.Join(_env.WebRootPath, category.Logo.Replace('/', '\\'));
                    System.IO.File.Delete(path);

                    // modificam informatiile
                    category.CategoryName = requestCategory.CategoryName;

                    if (file != null && file.Length > 0)
                    {
                        category.Logo = res;

                    }

                    //commit
                    db.SaveChanges();

                    TempData["message"] = "The category has been edited";
                    TempData["messageType"] = "alert-success";
                    return RedirectToAction("Index");
                }
                else
                {
                    TempData["message"] = "You're unable to modify a category you didn't add!";
                    TempData["messageType"] = "alert-danger";
                    return RedirectToAction("Index");
                }
           
            }
            else
            {
                return View(requestCategory);
            }
        }

        [Authorize(Roles = "Admin,Moderator")]
        [HttpPost]
        public ActionResult Delete(int id)
        {
            // preluam categoria care trebuie stearsa
            Category category = db.Categories.Include("Exercises")
                                             .Where(c => c.Id == id)
                                             .First();

            if(category.UserId == _userManager.GetUserId(User) || User.IsInRole("Admin"))
            {
                // stergem imaginea logo din folder-ul imgs
                string path = Path.Join(_env.WebRootPath, category.Logo.Replace('/', '\\'));
                System.IO.File.Delete(path);

                // stergem categoria din baza de date
                db.Categories.Remove(category);

                // commit
                db.SaveChanges();

                TempData["message"] = "The category has been deleted";
                TempData["messageType"] = "alert-success";
                return RedirectToAction("Index");
            } 
            else
            {
                TempData["message"] = "You're unable to delete a category you didn't add!";
                TempData["messageType"] = "alert-danger";
                return RedirectToAction("Index");
            }
            
        }

        private async Task<string?> SaveImage(IFormFile file)
        {
            if (file == null)
            {
                return null;
            }

            var allowedExtensions = new[] { ".jpg", ".jpeg", ".png", ".gif" };
            var fileExtension = Path.GetExtension(file.FileName).ToLowerInvariant();
            if (!allowedExtensions.Contains(fileExtension))
            {
                return null;
            }

            var uploadsFolder = Path.Combine("img", "categories");
            var webRootPath = _env.WebRootPath;

            var uploadsFolderPath = Path.Combine(webRootPath, uploadsFolder);

            if (!Directory.Exists(uploadsFolderPath))
            {
                Directory.CreateDirectory(uploadsFolderPath);
            }

            var uniqueFileName = $"{Guid.NewGuid().ToString()}{fileExtension}";
            var filePath = Path.Combine(uploadsFolderPath, uniqueFileName);

            using (var fileStream = new FileStream(filePath, FileMode.Create))
            {
                await file.CopyToAsync(fileStream);
            }

            var relativeFilePath = Path.Combine(uploadsFolder, uniqueFileName).Replace(Path.DirectorySeparatorChar, '/');
            return $"/{relativeFilePath}";
        }

        public IActionResult GetAllCategories()
        {
            var categories = _categoryRepository.GetAllCategories();
            return View(categories);
        }

Developer-Toolbox/Views/Categories/Edit.cshtml
@model Developer_Toolbox.Models.Category

<link rel="stylesheet" href="~/css/form.css" asp-append-version="true" />



<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-lg-10 col-md-12 col-sm-12">
            <div class="card shadow-lg">
                <div class="card-body">
                    <h3 class="card-title text-center mb-4">Edit category</h3>
                    <form method="post" enctype="multipart/form-data" action="/Categories/Edit/@Model.Id">
                        <div class="mb-3">
                            @Html.Label("CategoryName", "Category Name")

                            @Html.TextBox("CategoryName", null, new { @class = "form-control" })

                            @Html.ValidationMessageFor(m => m.CategoryName, null, new{ @class = "text-danger"})
                        </div>
                        <div class="mb-3">
                            <div>
                                <label for="file" class="form-label">Upload Logo</label>
                                <input type="file" class="form-control" id="file" name="file" />
                                @Html.ValidationMessage("Logo", null, new { @class = "text-danger" })
                            </div>
                        </div>
                        <!-- Submit Button -->
                        <div class="text-center">
                            <button type="submit" class="btn btn-primary btn-lg">Save changes</button>
                            <div id="formFeedback" class="mt-3"></div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

Developer-Toolbox/Views/Categories/Index.cshtml
<link rel="stylesheet" href="~/css/feature_section.css" asp-append-version="true" />
<link rel="stylesheet" href="~/css/categories.css" asp-append-version="true" />


<section class="features-area features-one">
    @if (TempData.ContainsKey("message"))
    {
        <h4 class="@ViewBag.MessageType p-3 rounded-3 text-center mb-5">@ViewBag.Message</h4>
    }
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-6">
                <div class="section-title text-center">
                    <h3 class="title">Explore coding exercises</h3>
                    <p class="text">
                        Choose from a variety of coding exercises organized according to their target domain. What skills do you want to improve today?
                    </p>
                </div>
                <!-- row -->
            </div>
        </div>
        <div class="row justify-content-center">
            <div class="col d-flex justify-content-end" style="margin-right: 2%">
 
                @if (ViewBag.IsAdmin || ViewBag.IsModerator)
                {
                    <a class="btn btn-outline-primary py-sm-3 px-sm-4 rounded-pill me-3" style="font-weight:bold;" href="/Categories/New" role="button"> + Add Category</a>
                }
            </div>
        </div>
        <!-- row -->
        <div class="container py-5">
            <div class="row g-5 d-flex justify-content-start">
                @foreach (var category in ViewBag.Categories) {
                    <div class="col" style="max-width: fit-content">
                        <div class="card category-card border-0 rounded-4 shadow-sm">
                            <div class="position-relative">
                                <div class="category-image">
                                    <img src="@category.Logo" class="img-fluid rounded-start" alt="@category.CategoryName">
                                </div>
                            </div>
                            <div class="card-body p-4 d-flex flex-column justify-content-around">
                                <h5 class="card-title mb-3 fw-bold text-center">@category.CategoryName</h5>
                               
                                @*if the user is the moderator that created the category or the admin is allowed to edit and delete*@
                                @if (category.UserId == ViewBag.CurrentUser || ViewBag.IsAdmin)
                                {
                                    <div style="display:flex; justify-content: space-between;">
                                        <a asp-action="Edit" asp-controller="Categories" asp-route-id="@category.Id" class="btn btn-no-outline">
                                            <i class="lni lni-write" style="font-size: x-large; color: var(--primary)"></i>
                                        </a>
                                        <a class="btn btn-outline-primary py-2 px-5 rounded-pill" style="font-weight: bold"
                                           asp-controller="Exercises" asp-action="Index" asp-route-id="@category.Id">
                                            Browse
                                        </a>
                                        <form method="post" asp-action="Delete" asp-controller="Categories" asp-route-id="@category.Id">
                                            <button type="submit" class="btn btn-no-outline">
                                                <i class="lni lni-trash-can" style="font-size: x-large; color: var(--primary)"></i>
                                            </button>
                                        </form>
                                    </div>
                                }
                                else
                                {
                                    <a class="btn btn-outline-primary py-2 px-5 rounded-pill" style="font-weight: bold"
                                       asp-controller="Exercises" asp-action="Index" asp-route-id="@category.Id">
                                        Browse
                                    </a>
                                }
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
    <!-- container -->
</section>

Developer-Toolbox/Views/Categories/New.cshtml
@model Developer_Toolbox.Models.Category

<link rel="stylesheet" href="~/css/form.css" asp-append-version="true" />


<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-lg-10 col-md-12 col-sm-12">
            <div class="card shadow-lg">
                <div class="card-body">
                    <h3 class="card-title text-center mb-4">Add new category</h3>
                    <form method="post" enctype="multipart/form-data" action="/Categories/New">
                        <div class="mb-3">
                            @Html.Label("CategoryName", "Category Name")

                            @Html.TextBox("CategoryName", null, new { @class = "form-control" })

                            @Html.ValidationMessageFor(m => m.CategoryName, null, new{ @class = "text-danger"})
                        </div>
                        <div class="mb-3">
                            <div>
                                <label for="file" class="form-label">Upload Logo</label>
                                <input type="file" class="form-control" id="file" name="file"/>
                                @Html.ValidationMessage("Logo", null, new { @class = "text-danger" })
                            </div>
                        </div>
                        <!-- Submit Button -->
                        <div class="text-center">
                            <button type="submit" class="btn btn-primary btn-lg">Submit</button>
                            <div id="formFeedback" class="mt-3"></div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>