Developer-Toolbox/Models/Tag.cs
using System.ComponentModel.DataAnnotations;

namespace Developer_Toolbox.Models
{
    public class Tag
    {
        [Key]
        public int Id { get; set; }
        public virtual ICollection<QuestionTag>? QuestionTags { get; set; }

        [Required(ErrorMessage ="The name field is required!")]
        public string? Name { get; set; }

        public virtual ICollection<BadgeTag>? BadgeTags { get; set; }

    }
}

Developer-Toolbox/Controllers/TagsController.cs
using Developer_Toolbox.Data;
using Developer_Toolbox.Models;
using Developer_Toolbox.Repositories;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Developer_Toolbox.Controllers
{
    public class TagsController : Controller
    {
        private readonly ApplicationDbContext db;

        private readonly UserManager<ApplicationUser> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly ITagRepository _tagRepository;

        public TagsController(ApplicationDbContext context,
            UserManager<ApplicationUser> userManager,
            RoleManager<IdentityRole> roleManager,
            ITagRepository tagRepository)
        {
            db = context;
            _userManager = userManager;
            _roleManager = roleManager;
            _tagRepository = tagRepository;
        }

        // Conditiile de afisare a butoanelor de editare si stergere
        private void SetAccessRights()
        {
            ViewBag.AfisareButoane = false;

            ViewBag.EsteAdmin = User.IsInRole("Admin");

            ViewBag.EsteModerator = User.IsInRole("Moderator");

            ViewBag.UserCurent = _userManager.GetUserId(User);
        }

        public IActionResult Index()
        {
            SetAccessRights();
            // get tags from database
            var tags = from tag in db.Tags
                       orderby tag.Name
                       select tag;

            // initialize a list of tags to be accessed from View
            ViewBag.Tags = tags;

            ViewBag.Message = TempData["message"];
            ViewBag.MessageType = TempData["messageType"];

            return View();
        }

        public IActionResult Show(int id)
        {
            // find a tag in DB

            var taggedQuestions = db.Tags
                        .Include(tag => tag.QuestionTags)
                            .ThenInclude(qt => qt.Question)
                        .FirstOrDefault(tag => tag.Id == id);

            ViewBag.taggedQuestions = taggedQuestions;

            ViewBag.Message = TempData["message"];
            ViewBag.MessageType = TempData["messageType"];

            return View(taggedQuestions);
        }

        [Authorize(Roles = "Moderator,Admin")]
        public ActionResult New()
        {
            // build a new object of type tag
            var tag = new Tag();

            return View(tag);
        }


        [Authorize(Roles = "Moderator,Admin")]
        [HttpPost]
        public ActionResult New(Tag tag)
        {
            if (ModelState.IsValid)
            {
                db.Tags.Add(tag);
                db.SaveChanges();
                TempData["message"] = "The tag has been added";
                TempData["messageType"] = "alert-success";
            }
            else
            {
                return View(tag);
            }

            return RedirectToAction("Index");
        }

        [Authorize(Roles = "Moderator,Admin")]
        public IActionResult Edit(int id)
        {
            Tag tag = db.Tags.Find(id);

            return View(tag);
        }

        [Authorize(Roles = "Moderator,Admin")]
        [HttpPost]
        public ActionResult Edit(int id, Tag requestTag)
        {
            //find the tag object to be edited
            Tag tag = db.Tags.Find(id);

            if (ModelState.IsValid)
            {
                //change its attributes accordingly
                tag.Name = requestTag.Name;

                //commit
                db.SaveChanges();

                TempData["message"] = "The tag has been edited";
                TempData["messageType"] = "alert-success";

                return RedirectToAction("Index");
            }
            return View(requestTag);
        }

        [Authorize(Roles = "Moderator,Admin")]
        [HttpPost]
        public ActionResult Delete(int id)
        {
            //find the tag object to be deleted
            Tag tag = db.Tags.Include("QuestionTags").Where(c => c.Id == id).First();

            //delete it from the database
            db.Tags.Remove(tag);

            //commit
            db.SaveChanges();

            TempData["message"] = "The tag has been deleted";
            TempData["messageType"] = "alert-danger";
            return RedirectToAction("Index");
        }


        // Noua metoda GetAllTags
        public IActionResult GetAllTags()
        {
            var tags = _tagRepository.GetAllTags();
            return View(tags);
        }

        // Noua metoda GetTagById
        public IActionResult GetTagById(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tag = _tagRepository.GetTagById(id);
            if (tag == null)
            {
                return NotFound();
            }

            return View(tag);
        }
    }
}

Developer-Toolbox/Views/Tags/Edit.cshtml
@model Developer_Toolbox.Models.Tag

<link rel="stylesheet" href="~/css/form.css" asp-append-version="true" />


<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-lg-10 col-md-12 col-sm-12">
            <div class="card shadow-lg">
                <div class="card-body">
                    <h3 class="card-title text-center mb-4">Edit tag</h3>
                    <form method="post" enctype="multipart/form-data" action="/Tags/Edit/@Model.Id">
                        <div class="mb-3">
                            @Html.Label("Name", "Tag Name")

                            @Html.TextBox("Name", null, new { @class = "form-control" })

                            @Html.ValidationMessageFor(m => m.Name, null, new{@class = "text-danger"})
                        </div>
                        <!-- Submit Button -->
                        <div class="text-center">
                            <button type="submit" class="btn btn-primary btn-lg">Save changes</button>
                            <div id="formFeedback" class="mt-3"></div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

Developer-Toolbox/Views/Tags/Index.cshtml
<link rel="stylesheet" href="~/css/feature_section.css" asp-append-version="true" />

<section class="features-area features-one" style="min-height: 100vh">

    @if (TempData.ContainsKey("message"))
    {
        <h4 class="@ViewBag.MessageType p-3 rounded-3 text-center mb-5">@ViewBag.Message</h4>
    }
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-6">
                <div class="section-title text-center">
                    <h3 class="title">Explore tags</h3>
                    <p class="text">
                        Do you want to read question and answers or to share your knowledge on a specific topic? Check our tags!
                    </p>
                </div>
                <!-- row -->
            </div>
        </div>
        <div class="row justify-content-center">
            <div class="col d-flex justify-content-end" style="margin-right: 2%">
                <a class="btn btn-outline-primary py-sm-3 px-sm-4 rounded-pill me-3" style="font-weight:bold;" href="/Questions/Index" role="button"> + Ask Question</a>
                
                @if (ViewBag.EsteAdmin || ViewBag.EsteModerator)
                {
                    <a class="btn btn-outline-primary py-sm-3 px-sm-5 rounded-pill me-3" style="font-weight:bold;" href="/Tags/New" role="button"> + Add Tag</a>
                }
            </div>
        </div>
        <!-- row -->
        <div class="container py-5">
            <div class="row g-5 d-flex justify-content-start">
                @foreach (var tag in ViewBag.Tags)
                {
                    <div class="col" style="max-width: fit-content">
                        <div class="card category-card border-0 rounded-4 shadow-sm">
                            <div class="card-body p-4 d-flex flex-column justify-content-around">
                                <h5 class="card-title mb-3 fw-bold text-center">@tag.Name</h5>

                                @*if the user is the moderator that created the category or the admin is allowed to edit and delete*@
                                @if (ViewBag.EsteAdmin || ViewBag.EsteModerator)
                                {
                                    <div style="display:flex; justify-content: space-between;">
                                        <a asp-action="Edit" asp-controller="Tags" asp-route-id="@tag.Id" class="btn btn-no-outline">
                                            <i class="lni lni-write" style="font-size: x-large; color: var(--primary)"></i>
                                        </a>
                                        <a class="btn btn-outline-primary py-2 px-5 rounded-pill" style="font-weight: bold"
                                           asp-controller="Tags" asp-action="Show" asp-route-id="@tag.Id">
                                            Browse
                                        </a>
                                        <form method="post" asp-action="Delete" asp-controller="Tags" asp-route-id="@tag.Id">
                                            <button type="submit" class="btn btn-no-outline">
                                                <i class="lni lni-trash-can" style="font-size: x-large; color: var(--primary)"></i>
                                            </button>
                                        </form>
                                    </div>
                                }
                                else
                                {
                                    <a class="btn btn-outline-primary py-2 px-5 rounded-pill" style="font-weight: bold"
                                       asp-controller="Tags" asp-action="Show" asp-route-id="@tag.Id">
                                        Browse
                                    </a>
                                }
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
    <!-- container -->
</section>

Developer-Toolbox/Views/Tags/New.cshtml
@model Developer_Toolbox.Models.Tag

<link rel="stylesheet" href="~/css/form.css" asp-append-version="true" />

<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-lg-10 col-md-12 col-sm-12">
            <div class="card shadow-lg">
                <div class="card-body">
                    <h3 class="card-title text-center mb-4">Add tag</h3>
                    <form method="post" enctype="multipart/form-data" action="/Tags/New">
                        <div class="mb-3">
                            @Html.Label("Name", "Tag Name")

                            @Html.TextBox("Name", null, new { @class = "form-control" })

                            @Html.ValidationMessageFor(m => m.Name, null, new{ @class = "text-danger"})
                        </div>
                        
                        <!-- Submit Button -->
                        <div class="text-center">
                            <button type="submit" class="btn btn-primary btn-lg">Submit</button>
                            <div id="formFeedback" class="mt-3"></div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

Developer-Toolbox/Views/Tags/Show.cshtml
@model Developer_Toolbox.Models.Tag

<link rel="stylesheet" href="~/css/feature_section.css" asp-append-version="true" />
<link rel="stylesheet" href="~/css/questions.css" asp-append-version="true" />

<section class="features-area features-one">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-6">
                <div class="section-title text-center">
                    <h3 class="title">Tag: #@Model.Name</h3>
                    <p class="text">
                        Do you want to read question and answers or to share your knowledge on a specific topic? Check our tags!
                    </p>
                </div>
                <!-- row -->
            </div>
        </div>
        <div class="row justify-content-center">
            <div class="col d-flex justify-content-end" style="margin-right: 2%">
                <a class="btn btn-outline-primary py-sm-3 px-sm-4 rounded-pill me-3" style="font-weight:bold;" href="/Questions/Index" role="button"> + Ask Question</a>
            </div>
        </div>
        <!-- row -->
        <div class="container py-5">
            <div class="row g-5 d-flex justify-content-start">
                @foreach (var questionTag in Model.QuestionTags)
                {
                    <div class="col" style="max-width: fit-content">
                        <div class="card question-card border-0 rounded-4 shadow-sm">
                            <div class="card-body p-4 d-flex flex-column justify-content-around">
                                <h5 class="card-title mb-3 fw-bold text-center">@questionTag?.Question?.Title</h5>
                                <a class="btn btn-outline-primary py-2 px-5 rounded-pill" style="font-weight: bold"
                                   asp-controller="Questions" asp-action="Show" asp-route-id="@questionTag?.Question?.Id">
                                    Show
                                </a>
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
    <!-- container -->
</section>