Developer-Toolbox/Models/WeeklyChallenge.cs
using System.ComponentModel.DataAnnotations;
using Developer_Toolbox.Models.CustomValidations;


namespace Developer_Toolbox.Models
{
    public class WeeklyChallenge: IValidatableObject
    {
        [Key]
        public int Id { get; set; }

        public string? UserId { get; set; }

        [Required(ErrorMessage = "The title field is required!")]
        [StringLength(100, ErrorMessage = "The title cannot exceed 100 characters")]
        [MinLength(5, ErrorMessage = "The title must be at least 5 characters long")]
        public string Title { get; set; }
        [Required(ErrorMessage = "The description field is required!")]
        public string Description { get; set; }

        [Required(ErrorMessage = "Level of difficulty required!")]
        public string? Difficulty { get; set; }

        [Required(ErrorMessage = "Reward points are required.")]
        [Range(10, 1000, ErrorMessage = "Reward points must be between 10 and 1000.")]
        public int RewardPoints { get; set; }
        [Required(ErrorMessage = "Start date is required.")]
        public DateTime StartDate { get; set; } = DateTime.Now;

        [Required(ErrorMessage = "End date is required.")]
        public DateTime EndDate { get; set; } = DateTime.Now;

        // Relație Many-to-Many cu Exercise
        [MinimumCount(1, ErrorMessage = "At least one exercise is required.")]
        public virtual ICollection<WeeklyChallengeExercise>? WeeklyChallengeExercises { get; set; }

        public virtual ICollection<BadgeChallenge>? BadgeChallenges { get; set; }

        // Custom validation
        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        {
            if (EndDate < StartDate)
            {
                yield return new ValidationResult(
                    "End date cannot be earlier than start date.",
                    new[] { nameof(EndDate) }
                );
            }
        }
    }
}

Developer-Toolbox/Controllers/WeeklyChallengesController.cs
using Developer_Toolbox.Data;
using Developer_Toolbox.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc.Rendering;
using Developer_Toolbox.Interfaces;
using Hangfire;
using Developer_Toolbox.Repositories;

namespace Developer_Toolbox.Controllers
{
    public class WeeklyChallengesController : Controller
    {
        private readonly ApplicationDbContext db;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IRewardBadge _IRewardBadge;
        private readonly IEmailService _IEmailService;
        private readonly IRewardActivity _IRewardActivity;
        private readonly IWeeklyChallengeRepository _weeklyChallengeRepository;

        public WeeklyChallengesController(
            ApplicationDbContext context, 
            UserManager<ApplicationUser> userManager,
            IRewardBadge IRewardBadge,
            IEmailService IEmailService,
            IRewardActivity iRewardActivity,
            IWeeklyChallengeRepository weeklyChallengeRepository)
        {
            db = context;
            _userManager = userManager;
            _IRewardBadge = IRewardBadge;
            _IEmailService = IEmailService;
            _IRewardActivity = iRewardActivity;
            _weeklyChallengeRepository = weeklyChallengeRepository;
        }

        private void SetAccessRights()
        {
            ViewBag.AfisareButoane = false;
            ViewBag.EsteAdmin = User.IsInRole("Admin");
            ViewBag.UserCurent = _userManager.GetUserId(User);
            // verificam daca are profilul complet
            bool completeProfile = false;

            if (_userManager.GetUserId(User) != null)
            {
                // userConectat = true;
                if (db.ApplicationUsers.Find(_userManager.GetUserId(User)).FirstName != null)
                    completeProfile = true;
            }

            ViewBag.CompleteProfile = completeProfile;
        }

        public IActionResult Index()
        {
            SetAccessRights();

            // Preluăm datele din baza de date
            var weeklyChallenges = db.WeeklyChallenges
                                      .OrderByDescending(wc => wc.StartDate);
            // MOTOR DE CAUTARE

            var search = "";
            if (Convert.ToString(HttpContext.Request.Query["search"]) != null)
            {
                search = Convert.ToString(HttpContext.Request.Query["search"]).Trim();
                // Cautare challenge(dupa titlu si descriere)
                weeklyChallenges = db.WeeklyChallenges
                    .Where(wc => wc.Title.Contains(search) || wc.Description.Contains(search))
                    .OrderByDescending(wc => wc.StartDate);

            }

            //AFISARE PAGINATA

            // Alegem sa afisam 3 articole pe pagina
            int _perPage = 3;

            if (TempData.ContainsKey("message"))
            {
                ViewBag.Message = TempData["message"];
                ViewBag.MessageType = TempData["messageType"];
            }


            // Fiind un numar variabil de intrebari, verificam de fiecare data utilizand 
            // metoda Count()

            int totalItems = weeklyChallenges.Count();


            // Se preia pagina curenta din View-ul asociat
            // Numarul paginii este valoarea parametrului page din ruta
            // /Questions/Index?page=valoare

            var currentPage = Convert.ToInt32(HttpContext.Request.Query["page"]);

            // Pentru prima pagina offsetul o sa fie zero
            // Pentru pagina 2 o sa fie 3 
            // Asadar offsetul este egal cu numarul de intrebari care au fost deja afisate pe paginile anterioare
            var offset = 0;

            // Se calculeaza offsetul in functie de numarul paginii la care suntem
            if (!currentPage.Equals(0))
            {
                offset = (currentPage - 1) * _perPage;
            }

            // Se preiau intrebarile corespunzatoare pentru fiecare pagina la care ne aflam 
            // in functie de offset
            var paginatedWeeklyChallenges = weeklyChallenges.Skip(offset).Take(_perPage);


            // Preluam numarul ultimei pagini

            ViewBag.lastPage = Math.Ceiling((float)totalItems / (float)_perPage);

            // Trimitem intrebarile cu ajutorul unui ViewBag catre View-ul corespunzator
            ViewBag.WeeklyChallenges = paginatedWeeklyChallenges;

            if (search != "")
            {
                ViewBag.PaginationBaseUrl = "/WeeklyChallenges/Index/?search=" + search + "&page";
            }
            else
            {
                ViewBag.PaginationBaseUrl = "/WeeklyChallenges/Index/?page";
            }

            return View();
        }

        // Formular pentru un nou WeeklyChallenge
        [Authorize(Roles = "Admin")]
        public IActionResult New()
        {
            WeeklyChallenge weeklyChallenge = new WeeklyChallenge
            {
                StartDate = DateTime.Now
            };

            if (!User.Identity.IsAuthenticated)
            {
                return Redirect("/Identity/Account/Login");
            }

            var exercises = db.Exercises
                .Select(e => new { e.Id, e.Title })
                .ToList();

            ViewBag.Exercises = exercises;

            // setam dificultatile pentru dropdown
            List<string> optionsList = new List<string> { "Easy", "Intermediate", "Difficult" };

            // convertim List<string> in List<SelectListItem>
            List<SelectListItem> selectListItems = optionsList.Select(option =>
                new SelectListItem { Text = option, Value = option })
                .ToList();

            ViewBag.OptionsSelectList = selectListItems;

            return View(weeklyChallenge);
        }

        // POST: WeeklyChallenges/New
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]

        public IActionResult New(WeeklyChallenge weeklyChallenge, [FromForm] List<int> ExerciseIds)
        {

            if (!ModelState.IsValid)
            {
                // Dacă validarea modelului nu reușește, trimitem din nou datele către view.
                var exercises = db.Exercises.Select(e => new { e.Id, e.Title }).ToList();
                ViewBag.Exercises = exercises;
                List<string> optionsList = new List<string> {
                    DifficultyLevelsEnum.Easy.ToString(),
                    DifficultyLevelsEnum.Intermediate.ToString(),
                    DifficultyLevelsEnum.Difficult.ToString()
                };

                // convertim List<string> in List<SelectListItem>
                List<SelectListItem> selectListItems = optionsList.Select(option =>
                    new SelectListItem { Text = option, Value = option })
                    .ToList();

                ViewBag.OptionsSelectList = selectListItems;
                return View(weeklyChallenge);
            }
           

            try
            {

                // Inițializăm lista pentru relația Many-to-Many
                weeklyChallenge.WeeklyChallengeExercises = new List<WeeklyChallengeExercise>();

                foreach (var exerciseId in ExerciseIds)
                {
                    weeklyChallenge.WeeklyChallengeExercises.Add(new WeeklyChallengeExercise
                    {
                        ExerciseId = exerciseId
                    });
                }

                weeklyChallenge.UserId = _userManager.GetUserId(User);
                // Salvăm noul WeeklyChallenge
                db.WeeklyChallenges.Add(weeklyChallenge);
                db.SaveChanges();

                // Adăugăm job-ul Hangfire pentru notificarea utilizatorilor
                // Hangfire: notifică utilizatorii
/*                BackgroundJob.Enqueue(() => SendNotificationToUsers(weeklyChallenge.Id));*/

                _IRewardActivity.RewardActivity((int)ActivitiesEnum.ADD_CHALLENGE, _userManager.GetUserId(User));
                RewardBadgeForAddingChallenge().Wait();

                TempData["message"] = "The weekly challenge has been successfully added.";
                TempData["messageType"] = "alert-success";

                return RedirectToAction("Index"); // Redirect către pagina Index (sau alta acțiune)
            }
            catch (Exception ex)
            {
                TempData["message"] = "An error occurred while saving the weekly challenge.";
                TempData["messageType"] = "alert-danger";
                return View(weeklyChallenge);
            }
        }


        public IActionResult Show(int id)
        {
            SetAccessRights();

            // Preluăm WeeklyChallenge din baza de date, inclusiv exercițiile asociate
            var weeklyChallenge = db.WeeklyChallenges
                .Include(wc => wc.WeeklyChallengeExercises)
                .ThenInclude(wce => wce.Exercise)
                .FirstOrDefault(wc => wc.Id == id);

            if (weeklyChallenge == null)
            {
                TempData["message"] = "The requested Weekly Challenge does not exist.";
                TempData["messageType"] = "alert-danger";
                return RedirectToAction("Index");
            }

            // Lista de ExerciseIds asociate acestui WeeklyChallenge
            var exerciseIds = weeklyChallenge.WeeklyChallengeExercises
                .Select(wce => wce.ExerciseId)
                .ToList();

            // Obținem utilizatorul curent
            var userId = _userManager.GetUserId(User);

            // Numărul total de exerciții asociate provocării
            var nrTotal = exerciseIds.Count;

Developer-Toolbox/Views/WeeklyChallenges/Edit.cshtml
@model Developer_Toolbox.Models.WeeklyChallenge

<link rel="stylesheet" href="~/css/form.css" asp-append-version="true" />

<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-lg-10 col-md-12 col-sm-12">
            <div class="card shadow-lg">
                <div class="card-body">
                    <h3 class="card-title text-center mb-4">Edit Weekly Challenge</h3>
                    <form method="post" asp-action="Edit" asp-controller="WeeklyChallenges">
                        <input type="hidden" name="Id" value="@Model.Id" />

                        <div class="mb-3">
                            @Html.LabelFor(m => m.Title, "Challenge Title", new { @class = "form-label" })
                            @Html.TextAreaFor(m => m.Title, new { @class = "form-control" })
                            @Html.ValidationMessageFor(m => m.Title, "", new { @class = "text-danger" })
                        </div>
                        <div class="mb-3">
                            @Html.LabelFor(m => m.Description, "Challenge Description", new { @class = "form-label"})
                            @Html.TextAreaFor(m => m.Description, new { @class = "form-control" })
                            @Html.ValidationMessageFor(m => m.Description, "", new { @class = "text-danger" })
                        </div>
                        <div class="mb-3">
                            @Html.Label("Level of difficulty")
                            @Html.DropDownListFor(
                            (m => m.Difficulty),
                            (IEnumerable<SelectListItem>)ViewBag.OptionsSelectList,
                            "Select",
                            new { @class = "form-control" }
                            )
                        </div>
                        <div class="mb-3">
                            @Html.LabelFor(m => m.RewardPoints, "Reward Points", new { @class = "form-label"}) 
                            <input type="number" class="form-control" asp-for="RewardPoints" min="1" max="1000" />
                            @Html.ValidationMessageFor(m => m.RewardPoints, "", new { @class = "text-danger" })
                        </div>
                        <div class="mb-3">
                            @Html.LabelFor(m => m.StartDate, "Start Date", new { @class = "form-label"})
                            <input type="date" class="form-control" asp-for="StartDate" value="@Model.StartDate.ToString("yyyy-MM-dd")" />
                            @Html.ValidationMessageFor(m => m.StartDate, "", new { @class = "text-danger" })
                        </div>
                        <div class="mb-3">
                            @Html.LabelFor(m => m.EndDate, "End Date", new { @class = "form-label" })
                            <input type="date" class="form-control" asp-for="EndDate" value="@Model.EndDate.ToString("yyyy-MM-dd")" />
                            @Html.ValidationMessageFor(m => m.EndDate, "", new { @class = "text-danger" })
                        </div>
                        <div class="mb-3">
                            <label>Select Exercises</label>
                            @foreach (var exercise in ViewBag.Exercises)
                            {
                                <div class="form-check">
                                    <input type="checkbox" name="ExerciseIds" value="@exercise.Id"
                                           class="form-check-input"
                                    @(Model.WeeklyChallengeExercises.Any(wce => wce.ExerciseId == exercise.Id) ? "checked" : "") />
                                    <label for="exercise-@exercise.Id" class="form-check-label">@exercise.Title</label>
                                </div>
                            }
                            @Html.ValidationMessageFor(m => m.WeeklyChallengeExercises, "", new { @class = "text-danger" })
                        </div>

                        <!-- Submit Button -->
                        <div class="text-center">
                            <button type="submit" class="btn btn-primary btn-lg">Save changes</button>
                            <div id="formFeedback" class="mt-3"></div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

Developer-Toolbox/Views/WeeklyChallenges/Index.cshtml
<link rel="stylesheet" href="~/css/challenges.css" asp-append-version="true" />
<link rel="stylesheet" href="~/css/feature_section.css" asp-append-version="true" />

<section class="features-area features-one" style="min-height: 100vh">
    @if (TempData.ContainsKey("message"))
    {
        <h4 class="@ViewBag.MessageType p-3 rounded-3 text-center mb-5">@ViewBag.Message</h4>
    }
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-6">
                <div class="section-title text-center">
                    <h3 class="title">Weekly challenges</h3>
                </div>
                <!-- row -->
            </div>
        </div>
        <div class="row justify-content-center">
            <div class="col d-flex justify-content-between align-items-center" style="margin-right: 2%">
                <form method="GET" id="filterForm" class="d-flex justify-content-between align-items-center" style="padding-left: 1rem">
                    <div class="search-wrapper">
                        <div class="search-box">
                            <i class="fas fa-search search-icon"></i>
                            <input type="text" class="form-control search-input" placeholder="Search anything..." name="search" value="@ViewBag.SearchString">
                            <button class="btn btn-primary search-button" type="submit">
                                Search
                            </button>
                        </div>
                    </div>
                </form>
                @if (ViewBag.EsteAdmin)
                {
                    <a class="btn btn-outline-primary py-sm-3 px-sm-4 rounded-pill me-3" style="font-weight:bold;" href="/WeeklyChallenges/New" role="button"> + Add Challenge</a>
                }
            </div>
        </div>
        <!-- row -->
        <div class="container py-5">
            <div class="row g-5 d-flex justify-content-start">
                @foreach (var challenge in ViewBag.WeeklyChallenges)
                {
                    <div class="col" style="max-width: fit-content">
                        <div class="card challenge-card border-0 rounded-4 shadow-sm">
                            <div class="position-relative p-2 d-flex justify-content-between">
                                <span class="badge bg-primary badge-custom">@challenge.Difficulty</span>
                                <span class="badge badge-custom" style="color: var(--primary); border: 1px solid var(--primary)">@challenge.StartDate.ToString("yyyy-MM-dd") - @challenge.EndDate.ToString("yyyy-MM-dd")</span>
                            </div>
                            <div class="card-body p-4 d-flex flex-column justify-content-around">
                                <h5 class="card-title mb-3 fw-bold text-center">@challenge.Title</h5>
                                <p class="card-text text-center text-muted mb-4">
                                    @challenge.Description    
                                </p>


                                @if (ViewBag.EsteAdmin)
                                {
                                    <div style="display:flex; justify-content: space-between;">
                                        <a asp-action="Edit" asp-controller="WeeklyChallenges" asp-route-id="@challenge.Id" class="btn btn-no-outline">
                                            <i class="lni lni-write" style="font-size: x-large; color: var(--primary)"></i>
                                        </a>
                                        <a class="btn btn-outline-primary py-2 px-5 rounded-pill" style="font-weight: bold"
                                           asp-controller="WeeklyChallenges" asp-action="Show" asp-route-id="@challenge.Id">
                                            Solve
                                        </a>
                                        <form method="post" asp-action="DeleteConfirmed" asp-controller="WeeklyChallenges" asp-route-id="@challenge.Id">
                                            <button type="submit" class="btn btn-no-outline">
                                                <i class="lni lni-trash-can" style="font-size: x-large; color: var(--primary)"></i>
                                            </button>
                                        </form>                  
                                    </div>
                                }
                                else
                                {
                                    <a class="btn btn-outline-primary py-2 px-5 rounded-pill" style="font-weight: bold"
                                       asp-controller="WeeklyChallenges" asp-action="Show" asp-route-id="@challenge.Id">
                                        Solve
                                    </a>
                                }
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
    <!-- container -->

    <div class=" mb-2 d-flex justify-content-center ">
        <nav aria-label="Page navigation" style="color:#0d6efd">
            <ul class="pagination">
                <li class="page-item">
                    <a class="page-link" style="color:#0d6efd" href="/WeeklyChallenges/Index/@ViewBag.CategoryId?page=1&@ViewBag.QueryString" aria-label="Previous">
                        <span aria-hidden="true">&laquo;</span>
                    </a>
                </li>
                @for (int i = 1; i <= ViewBag.lastPage; i++)
                {
                    <li class="page-item"> <a class="page-link" style="color:#0d6efd" href="/WeeklyChallenges/Index/@ViewBag.CategoryId?page=@i&@ViewBag.QueryString">@(i)</a> </li>
                }
                <li class="page-item">
                    <a class="page-link" style="color:#0d6efd" href="/WeeklyChallenges/Index/@ViewBag.CategoryId?page=@(ViewBag.lastPage)&@ViewBag.QueryString" aria-label="Next">
                        <span aria-hidden="true">&raquo;</span>
                    </a>
                </li>
            </ul>
        </nav>
    </div>
</section>

Developer-Toolbox/Views/WeeklyChallenges/New.cshtml
@model Developer_Toolbox.Models.WeeklyChallenge

<link rel="stylesheet" href="~/css/form.css" asp-append-version="true" />


<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-lg-10 col-md-12 col-sm-12">
            <div class="card shadow-lg">
                <div class="card-body">
                    <h3 class="card-title text-center mb-4">Add new Weekly Challenge</h3>
                    <form method="post" asp-action="New" asp-controller="WeeklyChallenges">

                        <div class="mb-3">
                            @Html.LabelFor(m => m.Title, "Challenge Title", new { @class = "form-label" })
                            @Html.TextAreaFor(m => m.Title, new { @class = "form-control" })
                            @Html.ValidationMessageFor(m => m.Title, "", new { @class = "text-danger" })
                        </div>
                        <div class="mb-3">
                            @Html.LabelFor(m => m.Description, "Challenge Description", new { @class = "form-label"})
                            @Html.TextAreaFor(m => m.Description, new { @class = "form-control" })
                            @Html.ValidationMessageFor(m => m.Description, "", new { @class = "text-danger" })
                        </div>
                        <div class="mb-3">
                            @Html.Label("Level of difficulty")
                            @Html.DropDownListFor(
                            (m => m.Difficulty),
                            (IEnumerable<SelectListItem>)ViewBag.OptionsSelectList,
                            "Select",
                            new { @class = "form-control" }
                            )
                        </div>
                        <div class="mb-3">
                            @Html.LabelFor(m => m.RewardPoints, "Reward Points", new { @class = "form-label"})
                            <input type="number" class="form-control" asp-for="RewardPoints" min="1" max="1000" value="10" />
                            @Html.ValidationMessageFor(m => m.RewardPoints, "", new { @class = "text-danger" })
                        </div>
                        <div class="mb-3">
                            @Html.LabelFor(m => m.StartDate, "Start Date", new { @class = "form-label"})
                            <input type="date" class="form-control" asp-for="StartDate" value="@Model.StartDate.ToString("yyyy-MM-dd")" />
                            @Html.ValidationMessageFor(m => m.StartDate, "", new { @class = "text-danger" })
                        </div>
                        <div class="mb-3">
                            @Html.LabelFor(m => m.EndDate, "End Date", new { @class = "form-label" })
                            <input type="date" class="form-control" asp-for="EndDate" value="@Model.EndDate.ToString("yyyy-MM-dd")" />
                            @Html.ValidationMessageFor(m => m.EndDate, "", new { @class = "text-danger" })
                        </div>
                        <div class="mb-3">
                            <label>Select Exercises</label>
                            @foreach (var exercise in ViewBag.Exercises)
                            {
                                <div class="form-check">
                                    <input type="checkbox" name="ExerciseIds" value="@exercise.Id" class="form-check-input" id="exercise-@exercise.Id" />
                                    <label for="exercise-@exercise.Id" class="form-check-label">@exercise.Title</label>
                                </div>
                            }
                            @Html.ValidationMessageFor(m => m.WeeklyChallengeExercises, "", new { @class = "text-danger" })
                        </div>

                        <!-- Submit Button -->
                        <div class="text-center">
                            <button type="submit" class="btn btn-primary btn-lg">Submit</button>
                            <div id="formFeedback" class="mt-3"></div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

Developer-Toolbox/Views/WeeklyChallenges/Show.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    var challenge = ViewBag.WeeklyChallenge;
    var solutionsSummary = ViewBag.SolutionsSummary; // Raportul soluțiilor
}

<link rel="stylesheet" href="~/css/form.css" asp-append-version="true" />

<div class="container mt-5">
    @if (TempData.ContainsKey("message"))
    {
        <h4 class="@ViewBag.MessageType p-3 rounded-3 text-center mb-5">@ViewBag.Message</h4>
    }
    <div class="row justify-content-center">
        <div class="col-lg-10 col-md-12 col-sm-12">
            <div class="card shadow-lg">
                <div class="card-body">
                    <div class="position-relative p-2 d-flex justify-content-end">
                        <span class="badge bg-primary badge-custom fs-5">Progres: @solutionsSummary</span>
                    </div>
                    <h3 class="card-title text-center mb-4">@challenge.Title</h3>
                    <div class="mb-3 text-black">
                        <h5 class="py-2">Summary:</h5>
                        <p class="px-3 text-black">
                            <strong>Start Date:</strong> @challenge.StartDate.ToString("MMMM dd, yyyy")
                        </p>
                        <p class="px-3  text-black">
                            <strong>End Date:</strong> @challenge.EndDate.ToString("MMMM dd, yyyy")
                        </p>
                        <p class="px-3  text-black">
                            <strong>Difficulty:</strong> @challenge.Difficulty
                        </p>
                        <p class="px-3  text-black">
                            <strong>Reward Points:</strong> @challenge.RewardPoints
                        </p>
                        <hr />
                        <h5 class="py-2">Description:</h5>
                        <p class=" px-3  text-black">@challenge.Description</p>
                        <hr />
                        <h5 class="py-2">Exercises:</h5>
                        @if (challenge.WeeklyChallengeExercises != null && challenge.WeeklyChallengeExercises.Count > 0)
                        {
                            <ul class="list-group-flush">
                                @foreach (var exercise in challenge.WeeklyChallengeExercises)
                                {
                                    <li class="list-group-item" style="border: none;">
                                        <a href="/Exercises/Show/@exercise.Exercise.Id" class="text-decoration-none">
                                            @exercise.Exercise.Title
                                        </a>
                                    </li>
                                }
                            </ul>
                        }
                        else
                        {
                            <p class="text-muted">No exercises available for this challenge.</p>
                        }
                    </div>

                    <div class="d-flex justify-content-between align-items-center py-3">
                        <a href="/WeeklyChallenges/Index" class="btn btn-primary px-3 rounded-pill">Back to Challenges</a>

                        @if (ViewBag.EsteAdmin)
                        {
                            <!-- Button Container: Edit and Delete -->
                            <div class="d-flex gap-2">
                                <!-- Edit Button -->
                                <a href="/WeeklyChallenges/Edit/@challenge.Id" class="btn btn-outline-primary px-4 rounded-pill">Edit</a>

                                <!-- Delete Button -->
                                <form method="post" asp-action="DeleteConfirmed" asp-controller="WeeklyChallenges" asp-route-id="@challenge.Id" class="d-inline">
                                    <button type="submit" class="btn btn-outline-primary px-3 rounded-pill">Delete</button>
                                </form>
                            </div>
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>